language: java

jdk:
  - oraclejdk9

sudo: false

cache:
  directories:
  - $HOME/.gradle

install: /bin/true

before_script: cd src

script: gradlew test

after_success:
  - bash <(curl -s https://codecov.io/bash)