language: java

jdk:
  - oraclejdk9

sudo: false

cache:
  directories:
  - $HOME/.gradle

install: /bin/true

before_script: 
  - cd src
  - chmod +x gradlew

script: ./gradlew bintrayUpload -Pbuild.number=${TRAVIS_BUILD_NUMBER} -Pbintray_key=${BINTRAY_KEY}

after_success:
  - bash <(curl -s https://codecov.io/bash)